spring:
  application:
    name: gateway

zuul:
  routes:
    orders:
      service-id: order_status
      #url: http://localhost:8090
    messages:
      service-id: message_dispatcher
      #url: http://localhost:9000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

logging:
  level:
    root: INFO

#ribbon:
#  eureka:
#    enabled: false

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${server.port:8080}
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
